
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
   
    - name: Checkout code
      uses: actions/checkout@v4

   
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    
    - name: Build with Maven
      run: mvn clean install -DskipTests

   
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

   
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          hazallul/spring-boot-app-Test:${{ github.sha }}
          hazallul/spring-boot-app-Test:latest

   
    - name: Get current timestamp
      id: get_timestamp
      run: echo "timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT



    - name: Update restartedAt annotation with sed
      run: "sed -i 's/kubectl.kubernetes.io\\/restartedAt: \".*/kubectl.kubernetes.io\\/restartedAt: \"${{ steps.get_timestamp.outputs.timestamp }}\"/' Deployment.yaml"



    - name: Push changes
      run: |
       git config user.name "github-actions[bot]"
       git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
       git add Deployment.yaml
       git commit -m "Tarih güncellendi"
       git push https://x-access-token:${{ secrets.PAT }}@github.com/Hazallul/Deneme.git
      
